<?php

namespace App\Filament\Resources;

use App\Filament\Resources\AiReportResource\Pages;
use App\Models\AiReport;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class AiReportResource extends Resource
{
    protected static ?string $model = AiReport::class;
    protected static ?string $navigationIcon = 'heroicon-o-sparkles';
    protected static ?string $navigationGroup = 'AI';
    protected static ?string $modelLabel = 'AI Report';
    protected static ?string $pluralModelLabel = 'AI Reports';

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Section::make('Report')->columns(3)->schema([
                Forms\Components\Select::make('creator_id')->label('Creator')->relationship('creator', 'nickname')->searchable()->preload()->required(),
                Forms\Components\Select::make('report_type')->label('Report Type')->options([
                    'tracking' => 'Tracking',
                    'value_score' => 'Value Score',
                    'follow_up' => 'Follow-up',
                    'risk' => 'Risk',
                    'summary' => 'Summary',
                ])->default('tracking'),
                Forms\Components\TextInput::make('score')->label('Score')->numeric()->minValue(0)->maxValue(100)->default(0),
                Forms\Components\TextInput::make('grade')->label('Grade')->maxLength(10),
                Forms\Components\Select::make('generated_by')->label('Generated By')->relationship('generatedBy', 'name')->searchable()->preload(),
                Forms\Components\DateTimePicker::make('generated_at')->label('Generated At')->seconds(false),
                Forms\Components\Textarea::make('summary')->label('Summary')->rows(5)->required()->columnSpanFull(),
                Forms\Components\Textarea::make('risk_points')->label('Risk Points')->rows(4)->columnSpanFull(),
                Forms\Components\Textarea::make('next_steps')->label('Next Steps')->rows(4)->columnSpanFull(),
                Forms\Components\KeyValue::make('raw_payload')->label('Raw Payload')->columnSpanFull(),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('creator.nickname')->label('Creator')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('report_type')->label('Type')->badge(),
                Tables\Columns\TextColumn::make('score')->label('Score')->sortable()->badge(),
                Tables\Columns\TextColumn::make('grade')->label('Grade')->sortable(),
                Tables\Columns\TextColumn::make('generatedBy.name')->label('Generated By'),
                Tables\Columns\TextColumn::make('generated_at')->label('Generated At')->dateTime('Y-m-d H:i')->sortable(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAiReports::route('/'),
            'create' => Pages\CreateAiReport::route('/create'),
            'edit' => Pages\EditAiReport::route('/{record}/edit'),
        ];
    }
}
