<?php

namespace App\Filament\Resources;

use App\Filament\Resources\AiReportResource\Pages;
use App\Models\AiReport;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class AiReportResource extends Resource
{
    protected static ?string $model = AiReport::class;
    protected static ?string $navigationIcon = 'heroicon-o-sparkles';
    protected static ?string $navigationGroup = "AI\u{5206}\u{6790}";
    protected static ?string $modelLabel = "AI\u{62A5}\u{544A}";
    protected static ?string $pluralModelLabel = "AI\u{62A5}\u{544A}";

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Section::make(__('Report'))->columns(3)->schema([
                Forms\Components\Select::make('creator_id')->label(__('Creator'))->relationship('creator', 'nickname')->searchable()->preload()->required(),
                Forms\Components\Select::make('report_type')->label(__('Report Type'))->options([
                    'tracking' => __('Tracking'),
                    'value_score' => __('Value Score'),
                    'follow_up' => __('Follow-up'),
                    'risk' => __('Risk'),
                    'summary' => __('Summary'),
                ])->default('tracking'),
                Forms\Components\TextInput::make('score')->label(__('Score'))->numeric()->minValue(0)->maxValue(100)->default(0),
                Forms\Components\TextInput::make('grade')->label(__('Grade'))->maxLength(10),
                Forms\Components\Select::make('generated_by')->label(__('Generated By'))->relationship('generatedBy', 'name')->searchable()->preload(),
                Forms\Components\DateTimePicker::make('generated_at')->label(__('Generated At'))->seconds(false),
                Forms\Components\Textarea::make('summary')->label(__('Summary'))->rows(5)->required()->columnSpanFull(),
                Forms\Components\Textarea::make('risk_points')->label(__('Risk Points'))->rows(4)->columnSpanFull(),
                Forms\Components\Textarea::make('next_steps')->label(__('Next Steps'))->rows(4)->columnSpanFull(),
                Forms\Components\KeyValue::make('raw_payload')->label(__('Raw Payload'))->columnSpanFull(),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('creator.nickname')->label(__('Creator'))->searchable()->sortable(),
                Tables\Columns\TextColumn::make('report_type')->label(__('Type'))->badge(),
                Tables\Columns\TextColumn::make('score')->label(__('Score'))->sortable()->badge(),
                Tables\Columns\TextColumn::make('grade')->label(__('Grade'))->sortable(),
                Tables\Columns\TextColumn::make('generatedBy.name')->label(__('Generated By')),
                Tables\Columns\TextColumn::make('generated_at')->label(__('Generated At'))->dateTime('Y-m-d H:i')->sortable(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAiReports::route('/'),
            'create' => Pages\CreateAiReport::route('/create'),
            'edit' => Pages\EditAiReport::route('/{record}/edit'),
        ];
    }
}
